name: ChatGPT Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  code_review:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Ensure compatibility with the OpenAI library

    - name: Install openai library
      run: npm install openai@latest

    - name: Fetch PR Diff
      id: get_diff
      run: |
        git fetch origin ${{ github.event.pull_request.base.ref }}
        git diff origin/${{ github.event.pull_request.base.ref }} > pr_diff.txt

    - name: Run ChatGPT Review
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        # Create the review script
        echo "const fs = require('fs');
        const { OpenAI } = require('openai');

        const openai = new OpenAI({
          apiKey: process.env.OPENAI_API_KEY,
        });

        async function reviewCode() {
          try {
            const diff = fs.readFileSync('pr_diff.txt', 'utf8');
            const rules = fs.readFileSync('rules.md', 'utf8');

            const prompt = \`
              Review the following Pull Request diff against the rules below:
              Rules:
              \${rules}

              Diff:
              \${diff}

              Provide a summary of violations and suggestions for improvements.
            \`;

            const response = await openai.chat.completions.create({
              model: 'gpt-4',
              messages: [{ role: 'user', content: prompt }],
              max_tokens: 500,
            });

            const feedback = response.choices[0].message.content;
            console.log('ChatGPT Review Response:');
            console.log(feedback);

            // Save feedback to a file
            fs.writeFileSync('chatgpt_response.txt', feedback);
          } catch (error) {
            console.error('Error during ChatGPT review:', error);
            process.exit(1);
          }
        }

        reviewCode();" > review.js

        # Run the review script
        node review.js

    - name: Post Comments
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          const feedback = fs.readFileSync('chatgpt_response.txt', 'utf8');
          github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.payload.pull_request.number,
            body: feedback,
          });
