name: ChatGPT Inline Code Review

env:
  PR_NUMBER: ${{ github.event.pull_request.number }}
  GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions: 
  contents: write
  pull-requests: write
  repository-projects: write

jobs:
  code_review:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for accurate git blame

    - name: Restore PR Cache
      id: pr-cache
      uses: actions/cache@v3
      with:
        path: .github/cache/cache.json
        key: ${{ runner.os }}-pr-cache-${{ github.event.pull_request.number }}
        restore-keys: |
          ${{ runner.os }}-pr-cache-

    - name: Fetch PR Branch
      run: |
        git fetch origin ${{ github.event.pull_request.head.ref }}
        git checkout ${{ github.event.pull_request.head.ref }}

    - name: Cache Node.js Modules
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install Dependencies
      run: npm install openai @octokit/rest@18.12.0

    - name: Fetch PR Diff
      id: get_diff
      run: |
        git diff origin/${{ github.event.pull_request.base.ref }} -- '*.cs' '*.ts' '*.js' '*.sql' > pr_diff.txt

    - name: Initialize Cache if Missing
      run: |
        if [ ! -f .github/cache/cache.json ]; then
          mkdir -p .github/cache
          echo "{}" > .github/cache/cache.json
        fi

    - name: Generate ChatGPT Feedback
      id: generate_feedback
      run: node .github/scripts/generate_feedback.js

    - name: Save Updated PR Cache
      uses: actions/cache@v3
      with:
        path: .github/cache/cache.json
        key: ${{ runner.os }}-pr-cache-${{ github.event.pull_request.number }}

    - name: Post Inline Comments
      run: node .github/scripts/post_comments.js
