name: ChatGPT Inline Code Review

env:
  PR_NUMBER: ${{ github.event.pull_request.number }}
  GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions: 
  contents: write
  pull-requests: write
  repository-projects: write

jobs:
  code_review:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for accurate git blame

    # Step 3: Fetch PR Branch
    - name: Fetch PR Branch
      run: |
        git fetch origin ${{ github.event.pull_request.head.ref }}
        git checkout ${{ github.event.pull_request.head.ref }}

    # Step 4: Cache Node.js Modules
    - name: Cache Node.js Modules
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    # Step 5: Install Dependencies
    - name: Install Dependencies
      run: npm install openai @octokit/rest@18.12.0
  
    # Step 7: Fetch PR Diff
    - name: Fetch PR Diff
      id: get_diff
      run: |
        git diff origin/${{ github.event.pull_request.base.ref }} -- '*.cs' '*.ts' '*.js' '*.sql' > pr_diff.txt

    # Step 2: Restore PR Cache
    - name: Restore PR Cache
      id: pr-cache
      uses: actions/cache@v3
      with:
        path: .github/cache/cache.json
        key: ${{ runner.os }}-pr-cache-${{ github.event.pull_request.number }}
        restore-keys: |
          ${{ runner.os }}-pr-cache-

    # Step 6: Initialize Cache if Missing
    - name: Initialize Cache if Missing
      run: |
        if [ ! -f .github/cache/cache.json ] || [ ! -s .github/cache/cache.json ]; then
          echo "Cache file not found or empty. Initializing new cache."
          mkdir -p .github/cache
          echo "{}" > .github/cache/cache.json
        else
          echo "Cache file exists and contains data:"
          cat .github/cache/cache.json
        fi
    # Step 8: Generate ChatGPT Feedback
    - name: Generate ChatGPT Feedback
      id: generate_feedback
      run: node .github/scripts/generate_feedback.js

    # Step 10: Post Inline Comments
    - name: Post Inline Comments
      run: node .github/scripts/post_comments.js

    - name: Debug Restored Cache
      run: |
        if [ -f .github/cache/cache.json ]; then
          echo "Cache file exists after restore:"
          cat .github/cache/cache.json
        else
          echo "Cache file does not exist after restore."
        fi
